In [19]:
import numpy as np


a = np.array([1,1,0])
b = np.array([-1,2,5])
M = np.array([[2,-1,0],
            [-1,2,-1],
            [0,-1,2]])
9/32+3/4


1.03125

In [8]:
def inner_product(a,b):
    """Given two vectors a and b, calculates their inner product"""
    
    return np.sum([a[i]*b[i] for i in range(len(a))])

inner_prod = inner_product(a, b)
assert (inner_prod == np.dot(a,b)), 'The computation does not match with results from numpy library'
print('a) inner product between a and b =', np.dot(a,b))
    

a) inner product between a and b = 1


In [9]:
def matrix_vector_product(A, b):
    """Given a matrix A and a vectors b, calculates the matrix vector product Ab """
    
    n = len(b)
    assert (len(A[0])== n), 'The size of matrix and vector are not compatible'
    
    res = []
    for i in range(n):
        res.append(np.sum([A[i][j]*b[j] for j in range(n)]))
    return res

matrix_vec_prod = matrix_vector_product(M, b)

assert (matrix_vec_prod == np.dot(M,b)).all(), 'The computation does not match with results from numpy library'

print('b) matrix-vector product between M and b =', matrix_vec_prod)
    

b) matrix-vector product between M and b = [-4, 0, 8]


In [10]:
def l_2_norm(a):
    """Given a vector a, calculates its l_2 norm"""
    
    return np.sqrt(np.sum(np.square(b)))
l2_norm = l_2_norm(b)
print('l_2 norm of b =', l2_norm)


l_2 norm of b = 5.477225575051661


In [11]:
def lu_decompisition(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    U = U.astype('float64')
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U

def forward_sub(L, b):
    """Given a lower triangular matrix L and right-side vector b,
    compute the solution vector y solving Ly = b."""

    y = []
    for i in range(len(b)):
        y.append(b[i])
        for j in range(i):
            y[i]=y[i]-(L[i, j]*y[j])
        y[i] = y[i]/L[i, i]

    return y

def backward_sub(U, y):
    """Given a lower triangular matrix U and right-side vector y,
    compute the solution vector x solving Ux = y."""

    x = np.zeros_like(y)

    for i in range(len(x), 0, -1):
        x[i-1] = (y[i-1] - np.dot(U[i-1, i:], x[i:])) / U[i-1, i-1]
    return x



def lu_solve(L, U, b):
    y = forward_sub(L,b)
    x = backward_sub(U,y)
    return x


def linear_solve(A, b):
    # ...
    L, U = lu_decompisition(A)
    x = lu_solve(L,U,b)
    return x

L, U = lu_decompisition(M)
print('\n Lower Triangular Matrix, L: \n', L)
print('\n Upper Triangular Matrix, U: \n\n', U)
assert(np.matmul(L,U).round(decimals = 2) == M).all(), 'LU Decomposition is incorrect'

res = linear_solve(M,b)
print('\n The solution, x = ', res)


 Lower Triangular Matrix, L: 
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]

 Upper Triangular Matrix, U: 

 [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]

 The solution, x =  [1.5 4.  4.5]


In [12]:
def cholesky_decomposition(A):
    """Performs a Cholesky decomposition of A, which must 
    be a symmetric and positive definite matrix. The function
    returns the lower variant triangular matrix, L."""
    n = len(A)

    # Create zero matrix for L
    L = np.array([[0.0] * n for i in range(n)])

    # Perform the Cholesky decomposition
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): # Diagonal elements
                L[i][k] = np.sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L

def Cholesky_solve(A, b):
    L = cholesky_decomposition(A)
    L_T = np.transpose(L)
    y = forward_sub(L,b)
    x = backward_sub(L_T,y)
    return x


L_tilda = cholesky_decomposition(M)
U_tilda = np.transpose(L_tilda)
print('\n Lower Triangular Matrix, L: \n', L_tilda)
print('\n Upper Triangular Matrix, U: \n\n', U_tilda)

assert(np.matmul(L_tilda,U_tilda).round(decimals = 2) == M).all(), 'Cholesky Decomposition is incorrect'

res = Cholesky_solve(M,b)
print('\n The solution, x = ', res)
    



 Lower Triangular Matrix, L: 
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]

 Upper Triangular Matrix, U: 

 [[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]

 The solution, x =  [1.5 4.  4.5]
